### PR TITLE
helpers: improve exception message for project and machine configuration files

### PR DESCRIPTION
**Pull request by gqueiroz**

### CODE REVIEW

**Comment by gqueiroz** [comment]
Looks like [Travis CI job](https://travis-ci.org/github/inveniosoftware/invenio-cli/jobs/710596603) failed in the first attempt due to the `isort` call during `./run-tests.sh` execution:
- `isort: error: argument -f/--future: expected one argument`

Maybe this is related to release of `isort 5`: [Upgrading to 5.0.0](https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/)

In the commit I suggested using this:
- `isort . --check-only --diff ` instead of `isort -rc -c -df` in `./run-tests.sh`.

but I am not sure if it would be safer to use a specific list of directories instead of `.` to avoid inclusion of *venvs*.

**Comment by ppanero** [comment]
Hi @gqueiroz!

Thanks for the PR! IMHO I would use module name and tests, it's mainly where there are python files:

`isort invenio_cli tests --check-only --diff`

WDYT?

**Comment by gqueiroz** [comment]
Hi @ppanero,

I totally agree!
May I change that in the PR and send it again?

**Comment by ppanero** [comment]
Thanks a lot @gqueiroz! will be merged soon.

**Pull request merged**
